/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChatArea: typeof import('./src/components/chat/ChatArea.vue')['default']
    ChatAreaText: typeof import('./src/components/core/chatAreaText.vue')['default']
    ChatCore: typeof import('./src/components/core/chatCore.vue')['default']
    ChatPage: typeof import('./src/components/core/chatPage.vue')['default']
    CodeBlock: typeof import('./src/components/chat/CodeBlock.vue')['default']
    CodeBlockUp: typeof import('./src/components/ui/codeBlockUp.vue')['default']
    CommandExecution: typeof import('./src/components/c-command/CommandExecution.vue')['default']
    CommandExecutionError: typeof import('./src/components/c-command/CommandExecutionError.vue')['default']
    CommandPatternSelector: typeof import('./src/components/c-command/CommandPatternSelector.vue')['default']
    CoreLayout: typeof import('./src/components/layout/coreLayout.vue')['default']
    DemoRightPanel: typeof import('./src/components/panels/DemoRightPanel.vue')['default']
    FilePanel: typeof import('./src/components/panels/FilePanel.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    LeftSidebar: typeof import('./src/components/layout/leftSidebar.vue')['default']
    MarkdownBlock: typeof import('./src/components/chat/MarkdownBlock.vue')['default']
    MarkdownTest: typeof import('./src/components/chat/MarkdownTest.vue')['default']
    MermaidBlock: typeof import('./src/components/chat/MermaidBlock.vue')['default']
    MessageContent: typeof import('./src/components/chat/MessageContent.vue')['default']
    MessageInput: typeof import('./src/components/chat/MessageInput.vue')['default']
    MessageItem: typeof import('./src/components/chat/MessageItem.vue')['default']
    ProcessPanel: typeof import('./src/components/panels/ProcessPanel.vue')['default']
    RightPanel: typeof import('./src/components/panels/RightPanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StudioContainer: typeof import('./src/components/core/studioContainer.vue')['default']
    TodoListDisplay: typeof import('./src/components/chat/TodoListDisplay.vue')['default']
    ToolCallDisplay: typeof import('./src/components/chat/ToolCallDisplay.vue')['default']
    Tooltip: typeof import('./src/components/ui/Tooltip.vue')['default']
  }
}
